# Generated by ChatGPT for BabyStats_backend

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="SleepTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("length", models.PositiveIntegerField(help_text="Length in minutes")),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sleep_times", to="rest_api.child"),
                ),
            ],
        ),
    ]
