# Generated by Django 6.0.1 on 2026-01-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeptime',
            name='time',
            field=models.TimeField(blank=True, help_text='Time when the sleep occurred', null=True),
        ),
        migrations.AlterField(
            model_name='sleeptime',
            name='length',
            field=models.PositiveIntegerField(help_text='Length in seconds'),
        ),
    ]
