# Generated by ChatGPT on 2026-01-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_sleeptime_time_alter_sleeptime_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date/time of the activity')),
                ('length', models.PositiveIntegerField(help_text='Length in seconds')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rest_api.child')),
                ('tags', models.ManyToManyField(blank=True, related_name='activities', to='rest_api.tag')),
            ],
        ),
    ]
